using System;
using Newtonsoft.Json;
using Лаба_3_2сем_;
Triangle Triangle1 = new Triangle(0,0,0,4,3,0);
Triangle Triangle2 = new Triangle(0, 0, 0, 4, 4, 0);
Console.WriteLine("Периметр трикутника1:" + Triangle1.TrianglePerimeter());
Console.WriteLine("Периметр трикутника2:" + Triangle2.TrianglePerimeter());
Console.WriteLine("Трикутник1=Трикутник2:" + Triangle1.Equals(Triangle2));
Console.WriteLine("Площа трикутника1:" + Triangle1.TriangleSquare());
Console.WriteLine("Площа трикутника2:" + Triangle2.TriangleSquare());
double[] heights1 = Triangle1.TriangleHeights();
Console.WriteLine("Висота a1:" + heights1[0]);
Console.WriteLine("Висота b1:" + heights1[1]);
Console.WriteLine("Висота c1:" + heights1[2]);
double[] heights2 = Triangle2.TriangleHeights();
Console.WriteLine("Висота a2:" + heights2[0]);
Console.WriteLine("Висота b2:" + heights2[1]);
Console.WriteLine("Висота c2:" + heights2[2]);
double [] medians1 = Triangle1.TriangleMedians();
Console.WriteLine("Медiана a1:" + medians1[0]);
Console.WriteLine("Медiана b1:" + medians1[1]);
Console.WriteLine("Медiана c1:" + medians1[2]);
double[] medians2 = Triangle2.TriangleMedians();
Console.WriteLine("Медiана a2:" + medians2[0]);
Console.WriteLine("Медiана b2:" + medians2[1]);
Console.WriteLine("Медiана c2:" + medians2[2]);
double[] Bisectors1 = Triangle1.TriangleBisectors();
Console.WriteLine("Бiсектриса a1:" + Bisectors1[0]);
Console.WriteLine("Бiсектриса b1:" + Bisectors1[1]);
Console.WriteLine("Бiсектриса c1:" + Bisectors1[2]);
double[] Bisectors2 = Triangle2.TriangleBisectors();
Console.WriteLine("Бiсектриса a2:" + Bisectors2[0]);
Console.WriteLine("Бiсектриса b2:" + Bisectors2[1]);
Console.WriteLine("Бiсектриса c2:" + Bisectors2[2]);
Console.WriteLine("Радiус1 вписаного кола:" + Triangle1.InscribedCircleRadius());
Console.WriteLine("Радiус1 oписаного кола:" + Triangle1.CircumscribedCircle());
Console.WriteLine("Радiус2 вписаного кола:" + Triangle2.InscribedCircleRadius());
Console.WriteLine("Радiус2 oписаного кола:" + Triangle2.CircumscribedCircle());
Console.WriteLine("Тип трикутника1:" + Triangle1.TriangleType());
Console.WriteLine("Тип трикутника2:" + Triangle2.TriangleType());
double angle;
Console.Write("Задайте кут повороту трикутника:");
angle = Double.Parse(Console.ReadLine());
Console.Write("Задайте вершину для повороту:");
string abc = Console.ReadLine();
Triangle1.RotateTriangle(angle, abc);
Triangle2.RotateTriangle(angle, abc);
Triangle.SaveToJson(Triangle1, "Triangle1.json");
Console.ReadKey();